global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@yourdomain.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    # Add your preferred notification method here
    # Examples: email, slack, discord webhook, etc.
    
    # Example Discord webhook (uncomment and configure)
    # discord_configs:
    # - webhook_url: 'YOUR_DISCORD_WEBHOOK_URL'
    #   title: 'Bot Alert'
    #   message: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    
    # Example email (uncomment and configure)
    # email_configs:
    # - to: 'admin@yourdomain.com'
    #   subject: 'Bot Alert: {{ .GroupLabels.alertname }}'
    #   body: |
    #     {{ range .Alerts }}
    #     Alert: {{ .Annotations.summary }}
    #     Description: {{ .Annotations.description }}
    #     {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']